options:
  # Global options
  intel-operator-release:
    type: string
    description: |
      Specify the version of intel-device-plugins-operator, see:
      https://github.com/intel/intel-device-plugins-for-kubernetes/releases

      example)
        juju config intel-device-plugins-k8s-operator intel-operator-release='v0.29.0'
      
      A list of supported versions is available through the action:
        juju run intel-device-plugins-k8s-operator/0 list-versions
      
      To reset by to the latest supported by the charm use:
        juju config intel-device-plugins-k8s-operator --reset intel-operator-release
      
      The current release deployed is available by viewing
        juju status intel-device-plugins-k8s-operator

  cert-manager-release:
    type: string
    description: |
      Specify the version of cert-manager, see:
      https://cert-manager.io/docs/releases/

      example)
        juju config intel-device-plugins-k8s-operator cert-manager-release='v1.14.5'
      
      A list of supported versions is available through the action:
        juju run intel-device-plugins-k8s-operator/0 list-versions
      
      To reset by to the latest supported by the charm use:
        juju config intel-device-plugins-k8s-operator --reset cert-manager-release
      
      The current release deployed is available by viewing
        juju status intel-device-plugins-k8s-operator