# Taken from https://github.com/intel/intel-device-plugins-for-kubernetes/blob/release-0.29/deployments/operator/samples/deviceplugin_v1_gpudeviceplugin.yaml

apiVersion: deviceplugin.intel.com/v1
kind: GpuDevicePlugin
metadata:
  name: gpudeviceplugin-sample
spec:
  image: intel/intel-gpu-plugin:0.29.0
  sharedDevNum: 10
  logLevel: 4
  enableMonitoring: true
  nodeSelector:
    intel.feature.node.kubernetes.io/gpu: "true"
