job_queue: REPLACE_QUEUE
output_timeout: 1800
provision_data:
  REPLACE_PROVISION_DATA
test_data:
  test_cmds: |

    # Exit immediately if a test fails
    set -e

    # Clone repo from appropriate branch/commit.
    ssh ubuntu@$DEVICE_IP '
      DEBIAN_FRONTEND=noninteractive sudo apt -y install git
      git clone -b REPLACE_BRANCH \
        https://github.com/canonical/intel-device-plugins-k8s-operator.git \
        ~ubuntu/intel-device-plugins-k8s-operator
      cd ~ubuntu/intel-device-plugins-k8s-operator
      echo "Current git branch: $(git branch --show-current)"
      echo "Latest commit:"
      git log --name-status HEAD^..HEAD
    '

    # Provision charm environment
    ssh ubuntu@$DEVICE_IP '
      sudo ~ubuntu/intel-device-plugins-k8s-operator/.github/testflinger/provision.sh
    '

    # Test 1: Verify that microk8s is installed
    ssh ubuntu@$DEVICE_IP '
      command -v microk8s
    '

    # Test 2: Verify that juju is installed
    ssh ubuntu@$DEVICE_IP '
      command -v juju
    '

    # Test 3: Verify that juju microk8s model is deployed
    ssh ubuntu@$DEVICE_IP '
      ~ubuntu/intel-device-plugins-k8s-operator/.github/testflinger/test-cmd-with-timeout.sh \
        juju status -m welcome-k8s
    '

    # Test 4: Verify that microk8s controller pod is ready
    ssh ubuntu@$DEVICE_IP '
      microk8s.kubectl -n controller-microk8s wait --for=condition=Ready pod/controller-0 --timeout=1200s
    '

    # Test 5: Run charm integration tests with tox
    ssh ubuntu@$DEVICE_IP '
      tox -e integration --conf ~ubuntu/intel-device-plugins-k8s-operator/tox.ini
    '
