name: Intel Device Plugins K8s Operator Unit and Integration Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-inclusive-naming-check:
    name: Inclusive naming
    uses: canonical/inclusive-naming/.github/workflows/woke.yaml@main
    with:
      fail-on-error: "true"
  
  lint-and-unit-tests:
    name: Lint and unit tests
    uses: charmed-kubernetes/workflows/.github/workflows/lint-unit.yaml@main
    with:
      python: "['3.10', '3.11']"
    needs:
      - call-inclusive-naming-check

  integration-tests-system-A:
    name: Integration tests A on Testflinger instance with Intel GPU(s)
    runs-on: [testflinger]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build job file from template
        env:
          BRANCH: ${{ github.head_ref || github.ref_name }}
          QUEUE: dell-precision-3470-c30322 #ADL iGPU + NVIDIA GPU
          PROVISION_DATA: "distro: jammy"
        run: |
          sed -e "s|REPLACE_BRANCH|${BRANCH}|" \
          -e "s|REPLACE_QUEUE|${QUEUE}|" \
          -e "s|REPLACE_PROVISION_DATA|${PROVISION_DATA}|" \
          ${GITHUB_WORKSPACE}/.github/testflinger/job-def.yaml > \
          ${GITHUB_WORKSPACE}/maas2.yaml
      - name: Submit testflinger job
        uses: canonical/testflinger/.github/actions/submit@main
        with:
          poll: true
          job-path: ${GITHUB_WORKSPACE}/maas2.yaml

  integration-tests-system-B:
    name: Integration tests B on Testflinger instance with Intel GPU(s)
    runs-on: [testflinger]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Build job file from template
        env:
          BRANCH: ${{ github.head_ref || github.ref_name }}
          QUEUE: dell-precision-5680-c31665 #RPL iGPU + Arc Pro A60M dGPU
          PROVISION_DATA: "url: http://10.102.196.9/somerville/Platforms/jellyfish-muk/X96_A00/dell-bto-jammy-jellyfish-muk-X96-20230419-19_A00.iso"
        run: |
          sed -e "s|REPLACE_BRANCH|${BRANCH}|" \
          -e "s|REPLACE_QUEUE|${QUEUE}|" \
          -e "s|REPLACE_PROVISION_DATA|${PROVISION_DATA}|" \
          ${GITHUB_WORKSPACE}/.github/testflinger/job-def.yaml > \
          ${GITHUB_WORKSPACE}/oemscript.yaml
      - name: Submit testflinger job
        uses: canonical/testflinger/.github/actions/submit@main
        with:
          poll: true
          job-path: ${GITHUB_WORKSPACE}/oemscript.yaml