name: Intel Device Plugins K8s Operator Unit and Integration Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-inclusive-naming-check:
    name: Inclusive naming
    uses: canonical/inclusive-naming/.github/workflows/woke.yaml@main
    with:
      fail-on-error: "true"
  
  lint-and-unit-tests:
    name: Lint and unit tests
    uses: charmed-kubernetes/workflows/.github/workflows/lint-unit.yaml@main
    with:
      python: "['3.10', '3.11']"
    needs:
      - call-inclusive-naming-check

  integration-tests:
    name: Integration tests on Testflinger instance with Intel GPU
    runs-on: [self-hosted, testflinger]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Submit testflinger job
        uses: canonical/testflinger/.github/actions/submit@main
        with:
          poll: true
          job-path: ${GITHUB_WORKSPACE}/.github/workflows/testflinger-job-def.yaml